#PBS -N DSTAT-SEQ
#PBS -q mei
#PBS -l nodes=1:ppn=48:r662,walltime=3:00:00

module load gcc/5.3.0
module load gcc/7.2.0

source /share/apps/intel/parallel_studio_xe_2019/compilers_and_libraries_2019/linux/bin/compilervars.sh intel64

#####SEQUENCIAL#######

cd /home/a82523/ESC/TP1/NPB3.3.1-MZ/NPB3.3-MZ-SER/
make clean
cp config/make.icc.def config/make.def
make suite


######lu-mz######
/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/lu-mz_A_intel.csv > /dev/null & bin/lu-mz.A.x > /home/a82523/ESC/TP1/Results/SEQ/Results/lu-mz_A_intel.txt
sleep 2
kill $!

/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/lu-mz_B_intel.csv > /dev/null & bin/lu-mz.B.x > /home/a82523/ESC/TP1/Results/SEQ/Results/lu-mz_B_intel.txt
sleep 2
kill $!

/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/lu-mz_C_intel.csv > /dev/null & bin/lu-mz.C.x > /home/a82523/ESC/TP1/Results/SEQ/Results/lu-mz_C_intel.txt
sleep 2
kill $!

######sp-mz######
/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/sp-mz_A_intel.csv > /dev/null & bin/sp-mz.A.x > /home/a82523/ESC/TP1/Results/SEQ/Results/sp-mz_A_intel.txt
sleep 2
kill $!

/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/sp-mz_B_intel.csv > /dev/null & bin/sp-mz.B.x > /home/a82523/ESC/TP1/Results/SEQ/Results/sp-mz_B_intel.txt
sleep 2
kill $!

/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/sp-mz_C_intel.csv > /dev/null & bin/sp-mz.C.x > /home/a82523/ESC/TP1/Results/SEQ/Results/sp-mz_C_intel.txt
sleep 2
kill $!

######bt-mz######
/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/bt-mz_A_intel.csv > /dev/null & bin/bt-mz.A.x > /home/a82523/ESC/TP1/Results/SEQ/Results/bt-mz_A_intel.txt
sleep 2
kill $!

/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/bt-mz_B_intel.csv > /dev/null & bin/bt-mz.B.x > /home/a82523/ESC/TP1/Results/SEQ/Results/bt-mz_B_intel.txt
sleep 2
kill $!

/home/a82523/dstat-0.7.2/dstat --cpu --mem --io --disk -n --fs --output /home/a82523/ESC/TP1/Results/SEQ/DStat/bt-mz_C_intel.csv > /dev/null & bin/bt-mz.C.x > /home/a82523/ESC/TP1/Results/SEQ/Results/bt-mz_C_intel.txt
sleep 2
kill $!
