#PBS -N MPSTAT-MPI
#PBS -q mei
#PBS -l nodes=2:ppn=32:r641,walltime=2:00:00

module load gcc/5.3.0
module load gcc/7.2.0

module load intel/2019
module load intel/openmpi_mx/1.8.4

cd /home/a82523/ESC/TP1/NPB3.3.1-MZ/NPB3.3-MZ-MPI/
make clean
make suite

#####MPI#######

export OMP_NUM_THREADS=16
for kernel in {"bt-mz","lu-mz","sp-mz"}
do
  for size in {"A","B","C"}
  do
    (ssh compute-641-20 mpstat -P ALL 1 > /home/a82523/ESC/TP1/CORE_USAGE/Temp/temp2.txt) &
    mpstat -P ALL 1 > /home/a82523/ESC/TP1/CORE_USAGE/Temp/temp.txt & mpirun -np 4 --bind-to hwthread --map-by ppr:2:node:pe=16 -x OMP_NUM_THREADS --mca mtl mx --mca pml cm bin/$kernel.$size.4 > /home/a82523/ESC/TP1/CORE_USAGE/MPI_HT_1/Res/$kernel.$size.txt
    sleep 1;
    kill -9 %2;
    kill -9 %1;
    cat /home/a82523/ESC/TP1/CORE_USAGE/Temp/temp.txt | gawk -f /home/a82523/ESC/TP1/mpstatAWK_OLD.awk > /home/a82523/ESC/TP1/CORE_USAGE/MPI_HT_1/$kernel.$size.csv
    cat /home/a82523/ESC/TP1/CORE_USAGE/Temp/temp2.txt | gawk -f /home/a82523/ESC/TP1/mpstatAWK_OLD.awk > /home/a82523/ESC/TP1/CORE_USAGE/MPI_HT_2/$kernel.$size.csv
    rm /home/a82523/ESC/TP1/CORE_USAGE/Temp/temp.txt
    rm /home/a82523/ESC/TP1/CORE_USAGE/Temp/temp2.txt
  done
done
